#!/usr/bin/env python
"""Sync deploy/matrix.yaml (ports) + hub tests.modules → stack/matrix.json + js/env-hosts.js.

`public_host` in the YAML is the loopback Stage/Prod fallback (`stage.{public_host}`).
On a public host, envNavItems follows the current product hostname.
Tests axis is hub `matrix.yaml` `tests.modules` — not clone deploy/matrix.yaml.
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = SCRIPTS.parents[1]  # ethalon/ or live clone root

def resolve_matrix() -> tuple[Path, Path]:
    """Return (yaml, status-server) for live clone or ethalon-in-monorepo."""
    local_yaml = ROOT / "deploy" / "matrix.yaml"
    local_status = ROOT / "deploy" / "services-status-server.py"
    if local_yaml.is_file() and local_status.is_file():
        return local_yaml, local_status
    live = ROOT.parent / "autotests-ai-multistack-app"
    live_yaml = live / "deploy" / "matrix.yaml"
    live_status = live / "deploy" / "services-status-server.py"
    if live_yaml.is_file() and live_status.is_file():
        return live_yaml, live_status
    raise SystemExit(
        f"STOP: deploy/matrix.yaml not found from {ROOT} "
        "(live clone deploy/ or sibling autotests-ai-multistack-app/deploy/)"
    )


OUT_JSON = (
    ROOT
    / "frontend"
    / "_shared"
    / "frontend-javascript-app"
    / "stack"
    / "matrix.json"
)
OUT_HOSTS = (
    ROOT
    / "frontend"
    / "_shared"
    / "frontend-javascript-app"
    / "js"
    / "env-hosts.js"
)
OUT_HOSTS_DTS = OUT_HOSTS.with_suffix(".d.ts")
FANOUT_DS = (
    ROOT
    / "frontend"
    / "typescript"
    / "frontend-typescript-react"
    / "vendor"
    / "ds"
)

ENV_HOSTS_JS = r"""/**
 * Generated by frontend/scripts/sync-stack-matrix.py
 * from deploy/matrix.yaml `public_host`. Do not edit.
 *
 * PUBLIC_HOST is the loopback fallback. On a public host, Stage/Prod follow
 * the current product hostname (strip leading `stage.`), not the multihost
 * matrix value — so ai-first.autotests.ai stays on that product.
 */

export const PUBLIC_HOST = __PUBLIC_HOST__;

export const PROD_ORIGIN = 'https://' + PUBLIC_HOST;
export const STAGE_ORIGIN = 'https://stage.' + PUBLIC_HOST;

/** @param {string} hostname */
function isLoopbackHost(hostname) {
  if (!hostname) {
    return true;
  }
  const host = hostname.toLowerCase();
  if (host === 'localhost' || host === '127.0.0.1' || host === '::1' || host === '[::1]') {
    return true;
  }
  return /^\d{1,3}(?:\.\d{1,3}){3}$/.test(host);
}

/**
 * Prod hostname of the current product.
 * `stage.ai-first.autotests.ai` → `ai-first.autotests.ai`; loopback → PUBLIC_HOST.
 * @param {string} [hostname]
 */
export function productHost(hostname) {
  const host =
    hostname ??
    (typeof location !== 'undefined' && location.hostname ? location.hostname : '');
  if (isLoopbackHost(host)) {
    return PUBLIC_HOST;
  }
  return host.startsWith('stage.') ? host.slice('stage.'.length) : host;
}

/** @param {string} [hostname] @returns {{ prod: string, stage: string }} */
export function envOrigins(hostname) {
  const host = productHost(hostname);
  return {
    prod: 'https://' + host,
    stage: 'https://stage.' + host,
  };
}

/** @param {string} [hostname] @returns {{ href: string, label: string, testid: string, match: 'host' }}[] */
export function envNavItems(hostname) {
  const origins = envOrigins(hostname);
  return [
    {
      href: origins.stage + '/',
      label: 'Stage',
      testid: 'header-nav-stage',
      match: 'host',
    },
    {
      href: origins.prod + '/',
      label: 'Prod',
      testid: 'header-nav-prod',
      match: 'host',
    },
  ];
}
"""

ENV_HOSTS_DTS = """\
/** Generated sibling of `env-hosts.js` — `PUBLIC_HOST` from deploy/matrix.yaml. */
export const PUBLIC_HOST: string;
export const PROD_ORIGIN: string;
export const STAGE_ORIGIN: string;
export function productHost(hostname?: string): string;
export function envOrigins(hostname?: string): { prod: string; stage: string };
export function envNavItems(hostname?: string): Array<{
  href: string;
  label: string;
  testid: string;
  match: 'host';
}>;
"""


def load_matrix(path: Path, status_server: Path) -> dict:
    spec = importlib.util.spec_from_file_location("services_status_server", status_server)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {status_server}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._load_yaml_lite(path)


def resolve_hub_matrix() -> Path | None:
    """Hub generate catalog: sibling matrix.yaml next to ethalon/ or the live clone."""
    for candidate in (
        ROOT.parent / "matrix.yaml",
        ROOT.parent.parent / "autotests-ai-multistack-home" / "matrix.yaml",
    ):
        if candidate.is_file():
            return candidate
    return None


def tests_from_hub(previous: list) -> list:
    hub = resolve_hub_matrix()
    if hub is None:
        return previous
    try:
        import yaml  # type: ignore
    except ImportError:
        print("WARN: PyYAML missing — keeping previous tests in matrix.json", file=sys.stderr)
        return previous
    data = yaml.safe_load(hub.read_text(encoding="utf-8")) or {}
    modules = (data.get("tests") or {}).get("modules") or []
    return [
        {
            "id": t["id"],
            "status": t.get("status", "active"),
            "language": t.get("language"),
            "module": t.get("module"),
            "layers": list(t.get("layers") or []),
        }
        for t in modules
        if t.get("id")
    ]


def public_host_of(data: dict, yaml_path: Path) -> str:
    host = str(data.get("public_host") or data.get("canonical_stack_host") or "").strip()
    if host:
        return host
    for raw in yaml_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("public_host:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    raise SystemExit(f"STOP: {yaml_path} missing public_host")


def main() -> int:
    matrix_path, status_server = resolve_matrix()
    data = load_matrix(matrix_path, status_server)
    public_host = public_host_of(data, matrix_path)
    previous_tests: list = []
    if OUT_JSON.is_file():
        try:
            previous_tests = list(json.loads(OUT_JSON.read_text(encoding="utf-8")).get("tests") or [])
        except json.JSONDecodeError:
            previous_tests = []
    tests = tests_from_hub(previous_tests)

    payload = {
        "public_host": public_host,
        "backends": [
            {
                "id": b["id"],
                "status": b.get("status", "active"),
                "language": b.get("language"),
                "module": b.get("module"),
            }
            for b in data.get("backends", [])
        ],
        "frontends": [
            {
                "id": f["id"],
                "status": f.get("status", "active"),
                "kind": f.get("kind"),
                "module": f.get("module"),
            }
            for f in data.get("frontends", [])
        ],
        "tests": tests,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    OUT_HOSTS.write_text(
        ENV_HOSTS_JS.replace("__PUBLIC_HOST__", repr(public_host)),
        encoding="utf-8",
    )
    OUT_HOSTS_DTS.write_text(ENV_HOSTS_DTS, encoding="utf-8")
    print(
        f"wrote {OUT_JSON.relative_to(ROOT)} + {OUT_HOSTS.relative_to(ROOT)} "
        f"(public_host={public_host} · {len(payload['backends'])} be · "
        f"{len(payload['frontends'])} fe · {len(payload['tests'])} tests)"
    )
    if FANOUT_DS.is_dir():
        dest_json = FANOUT_DS / "stack" / "matrix.json"
        dest_hosts = FANOUT_DS / "js" / "env-hosts.js"
        dest_dts = dest_hosts.with_suffix(".d.ts")
        dest_json.parent.mkdir(parents=True, exist_ok=True)
        dest_json.write_text(OUT_JSON.read_text(encoding="utf-8"), encoding="utf-8")
        dest_hosts.write_text(OUT_HOSTS.read_text(encoding="utf-8"), encoding="utf-8")
        dest_dts.write_text(OUT_HOSTS_DTS.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"fan-out {FANOUT_DS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
