#!/usr/bin/env python
"""Sync deploy/matrix.yaml → stack/matrix.json + js/env-hosts.js.

`public_host` in the YAML is the Stage/Prod header SSOT (`stage.{public_host}`).
"""
from __future__ import annotations

import importlib.util
import json
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
ROOT = SCRIPTS.parents[1]  # ethalon/ or live clone root

def resolve_matrix() -> tuple[Path, Path]:
    """Return (yaml, status-server) for live clone or ethalon-in-monorepo."""
    local_yaml = ROOT / "deploy" / "matrix.yaml"
    local_status = ROOT / "deploy" / "services-status-server.py"
    if local_yaml.is_file() and local_status.is_file():
        return local_yaml, local_status
    live = ROOT.parent / "autotests-ai-multistack-app"
    live_yaml = live / "deploy" / "matrix.yaml"
    live_status = live / "deploy" / "services-status-server.py"
    if live_yaml.is_file() and live_status.is_file():
        return live_yaml, live_status
    raise SystemExit(
        f"STOP: deploy/matrix.yaml not found from {ROOT} "
        "(live clone deploy/ or sibling autotests-ai-multistack-app/deploy/)"
    )


OUT_JSON = (
    ROOT
    / "frontend"
    / "_shared"
    / "frontend-javascript-app"
    / "stack"
    / "matrix.json"
)
OUT_HOSTS = (
    ROOT
    / "frontend"
    / "_shared"
    / "frontend-javascript-app"
    / "js"
    / "env-hosts.js"
)
OUT_HOSTS_DTS = OUT_HOSTS.with_suffix(".d.ts")

ENV_HOSTS_JS = """\
/**
 * Generated by frontend/scripts/sync-stack-matrix.py
 * from deploy/matrix.yaml `public_host`. Do not edit.
 *
 * Stage is the `stage.` prefix of that host — not a second YAML key.
 */

export const PUBLIC_HOST = {host!r};

export const PROD_ORIGIN = 'https://' + PUBLIC_HOST;
export const STAGE_ORIGIN = 'https://stage.' + PUBLIC_HOST;

/** @returns {{ href: string, label: string, testid: string, match: 'host' }}[] */
export function envNavItems() {{
  return [
    {{
      href: STAGE_ORIGIN + '/',
      label: 'Stage',
      testid: 'header-nav-stage',
      match: 'host',
    }},
    {{
      href: PROD_ORIGIN + '/',
      label: 'Prod',
      testid: 'header-nav-prod',
      match: 'host',
    }},
  ];
}}
"""

ENV_HOSTS_DTS = """\
/** Generated sibling of `env-hosts.js` — values come from deploy/matrix.yaml `public_host`. */
export const PUBLIC_HOST: string;
export const PROD_ORIGIN: string;
export const STAGE_ORIGIN: string;
export function envNavItems(): Array<{
  href: string;
  label: string;
  testid: string;
  match: 'host';
}>;
"""


def load_matrix(path: Path, status_server: Path) -> dict:
    spec = importlib.util.spec_from_file_location("services_status_server", status_server)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {status_server}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._load_yaml_lite(path)


def public_host_of(data: dict, yaml_path: Path) -> str:
    host = str(data.get("public_host") or data.get("canonical_stack_host") or "").strip()
    if host:
        return host
    for raw in yaml_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("public_host:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    raise SystemExit(f"STOP: {yaml_path} missing public_host")


def main() -> int:
    matrix_path, status_server = resolve_matrix()
    data = load_matrix(matrix_path, status_server)
    public_host = public_host_of(data, matrix_path)

    payload = {
        "public_host": public_host,
        "backends": [
            {
                "id": b["id"],
                "status": b.get("status", "active"),
                "language": b.get("language"),
                "module": b.get("module"),
            }
            for b in data.get("backends", [])
        ],
        "frontends": [
            {
                "id": f["id"],
                "status": f.get("status", "active"),
                "kind": f.get("kind"),
                "module": f.get("module"),
            }
            for f in data.get("frontends", [])
        ],
        "tests": [
            {
                "id": t["id"],
                "status": t.get("status", "active"),
                "language": t.get("language"),
                "module": t.get("module"),
                "layers": list(t.get("layers") or []),
            }
            for t in data.get("tests", [])
        ],
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    OUT_HOSTS.write_text(ENV_HOSTS_JS.format(host=public_host), encoding="utf-8")
    OUT_HOSTS_DTS.write_text(ENV_HOSTS_DTS, encoding="utf-8")
    print(
        f"wrote {OUT_JSON.relative_to(ROOT)} + {OUT_HOSTS.relative_to(ROOT)} "
        f"(public_host={public_host} · {len(payload['backends'])} be · "
        f"{len(payload['frontends'])} fe · {len(payload['tests'])} tests)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
