<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Tests.Csharp.NBomber</RootNamespace>
    <AssemblyName>tests-csharp-nbomber</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NBomber" Version="6.6.0" />
    <PackageReference Include="NBomber.Http" Version="6.2.1" />
  </ItemGroup>
</Project>
